before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: tftree
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: tftree
    homepage: https://github.com/busser/tftree
    description: Display your Terraform module call stack
    license: Apache-2.0
    tap:
      owner: busser
      name: homebrew-tap
    install: |
      bin.install "tftree"
    test: |
      system "#{bin}/tftree -version"
